[package]
name = "failure_perf_issue"
version = "0.1.0"
authors = ["Vasily Kirichenko <Vasily.Kirichenko@kaspersky.com>"]

[dependencies]
tokio-core = "0.1"
hyper = "0.11"
futures = "0.1"
serde = "*"
serde_json = "*"
serde_derive = "*"
failure = "*"